# Generated by Django 4.0.4 on 2022-05-21 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'bebida',
            },
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'pizza',
            },
        ),
        migrations.CreateModel(
            name='PizzaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.CharField(choices=[('B', 'B'), ('M', 'M'), ('G', 'G'), ('GG', 'GG')], max_length=2)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=4)),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infos', to='app.pizza')),
            ],
            options={
                'db_table': 'pizzaInfo',
            },
        ),
        migrations.CreateModel(
            name='BebidaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho', models.CharField(choices=[('350ml', '350ml'), ('600ml', '600ml'), ('1500ml', '1500ml'), ('2000ml', '2000ml')], max_length=6)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=4)),
                ('bebida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infos', to='app.bebida')),
            ],
            options={
                'db_table': 'bebidaInfo',
            },
        ),
    ]
